// Getters and Setters autogenerated, no need for Lombok
class CarDemo(make: String, model: String, val color: String): VehicleDemo(make, model) {

    override fun accelerate() {
        println("vroom vroom")
        if (make == "Mazda") println(";)")
        super.accelerate()
    }

    fun details() {
        println("This is a $color $make $model")
    }
}